spring:
  profiles:
    active: prod

---

spring:
  profiles: dev
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:quick_poll
    driver-class-name: org.h2.Driver
    username: sa
    password:
#db:
#  driver:
#   class:
#     name: org.h2.Driver
#  url: jdbc:h2:mem:quick_poll
#  username: sa
#  password:

---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3306/quick_poll?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: delphi78
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true



